# Generated by Django 5.2.7 on 2025-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='desctiption',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=True, null=True),
        ),
    ]
